export const recentSearchesKey = '@fastly/recent-searches';
export const defaultRecentSearches: string[] = [
  'Coca Cola',
  'Hamburguesa',
  'Pizza',
  'Cebada',
  'Helado',
  'Azúcar',
  'Arroz',
  'Milo',

  // 'Coca Cola',
  // 'Hamburguesa',
  // 'Pizza',
  // 'Cebada',
  // 'Helado',
  // 'Azúcar',
  // 'Arroz',
  // 'Milo',
  // 'Coca Cola',
  // 'Hamburguesa',
  // 'Pizza',
  // 'Cebada',
  // 'Helado',
  // 'Azúcar',
  // 'Arroz',
  // 'Milo',
  // 'Coca Cola',
  // 'Hamburguesa',
  // 'Pizza',
  // 'Cebada',
  // 'Helado',
  // 'Azúcar',
  // 'Arroz',
  // 'Milo',
  // 'Coca Cola',
  // 'Hamburguesa',
  // 'Pizza',
  // 'Cebada',
  // 'Helado',
  // 'Azúcar',
  // 'Arroz',
  // 'Milo',
  // 'Coca Cola',
  // 'Hamburguesa',
  // 'Pizza',
  // 'Cebada',
  // 'Helado',
  // 'Azúcar',
  // 'Arroz',
  // 'Milo',
  // 'Coca Cola',
  // 'Hamburguesa',
  // 'Pizza',
  // 'Cebada',
  // 'Helado',
  // 'Azúcar',
  // 'Arroz',
  // 'Milo',
  // 'Coca Cola',
  // 'Hamburguesa',
  // 'Pizza',
  // 'Cebada',
  // 'Helado',
  // 'Azúcar',
  // 'Arroz',
  // 'Milo',
];
