export const team = [
  {
    name: 'Jimmy Morales',
    description: 'CEO & Programador',
    avatar: '/assets/images/team/shair.jpg',
    facebook: '/shair-facebook',
    instagram: '/shair-instagram',
    whatsapp: '/shair-whatsapp',
  },
  {
    name: 'Miguel Galvez',
    description: 'Administración & Marketing',
    avatar: '/assets/images/team/shair.jpg',
    facebook: '/shair-facebook',
    instagram: '/shair-instagram',
    whatsapp: '/shair-whatsapp',
  },
  {
    name: 'Paula Leython',
    description: 'Directora de Operaciones',
    avatar: '/assets/images/team/shair.jpg',
    facebook: '/shair-facebook',
    instagram: '/shair-instagram',
    whatsapp: '/shair-whatsapp',
  },
  {
    name: 'Jennifer Ruiz',
    description: 'Diseñadora',
    avatar: '/assets/images/team/shair.jpg',
    facebook: '/shair-facebook',
    instagram: '/shair-instagram',
    whatsapp: '/shair-whatsapp',
  },
  {
    name: 'Iván Aguilar',
    description: 'Administración',
    avatar: '/assets/images/team/shair.jpg',
    facebook: '/shair-facebook',
    instagram: '/shair-instagram',
    whatsapp: '/shair-whatsapp',
  },
  {
    name: 'Diego Mostacero',
    description: 'Administrador',
    avatar: '/assets/images/team/shair.jpg',
    facebook: '/shair-facebook',
    instagram: '/shair-instagram',
    whatsapp: '/shair-whatsapp',
  },
  // {
  //   name: 'William Oliva',
  //   description: 'Porgramador & Analista',
  //   avatar: '/assets/images/team/shair.jpg',
  //   facebook: '/shair-facebook',
  //   instagram: '/shair-instagram',
  //   whatsapp: '/shair-whatsapp',
  // },
];
