import {OrderClass} from '@fastly/interfaces/app';

export const ordersPendingQueue: OrderClass[] = [
  {
    id: '1dede',
    order: {
      product: {
        id: '123dede',
        name: 'Pizza',
        price: 12,
        blurHash: '',
        couponId: '',
        createdAt: new Date().toString(),
        description: 'pizza familiar',
        image: 'sadsads',
        storeId: 'dasdsa',
        updatedAt: new Date().toString(),
      },
      address: {
        city: 'Chepen',
        createdAt: new Date().toString(),
        id: 'dadededesdas',
        instructions: 'a espaldas del colegio',
        street: 'Ricardo Palma',
        latitude: 234,
        longitude: 345,
        name: 'mi casa',
        tag: 'AMIGO',
        updatedAt: new Date().toString(),
        zip: '321321',
      },
      createdAt: 'Thu Sep 24 2022 21:40:00 GMT-0500 (Peru Standard Time)',
      deliveryPrice: 3,
      id: '312321212121d12',
      productId: '321312',
      quantity: 1,
      status: 'PENDING',
      updatedAt: new Date().toString(),
      userAddressId: '321312',
      userId: '21312321',
    },
    coordinates: {
      latitude: -7.2272033,
      longitude: -79.4294623,
    },
  },
  // {
  //   id: '12121233',
  //   order: {
  //     product: {
  //       id: '1212123333',
  //       name: 'Pizza',
  //       price: 12,
  //       blurHash: '',
  //       couponId: '',
  //       createdAt: new Date().toString(),
  //       description: 'pizza familiar',
  //       image: 'sadsads',
  //       storeId: 'das333dsa',
  //       updatedAt: new Date().toString(),
  //     },
  //     address: {
  //       city: 'Chepen',
  //       createdAt: new Date().toString(),
  //       id: 'das3321213das',
  //       instructions: 'a espaldas del colegio',
  //       street: 'Ricardo Palma',
  //       latitude: 234,
  //       longitude: 345,
  //       name: 'mi casa',
  //       tag: 'AMIGO',
  //       updatedAt: new Date().toString(),
  //       zip: '321321',
  //     },
  //     createdAt: 'Thu Sep 22 2022 16:14:13 GMT-0500 (Peru Standard Time)',
  //     deliveryPrice: 3,
  //     id: '312e311212',
  //     productId: '321312',
  //     quantity: 1,
  //     status: 'PENDING',
  //     updatedAt: new Date().toString(),
  //     userAddressId: '32133312',
  //     userId: '2131233321',
  //   },
  //   coordinates: {
  //     latitude: 321,
  //     longitude: 123,
  //   },
  // },
];
