export enum StoreCategory {
	LICORERIA = 'Licorería',
	RESTAURANTE = 'Restaurante',
	MASCOTAS = 'Mascotas',
	MODA = 'Moda',
	TECNOLOGIA = 'Tecnología',
	JUGUETERIA = 'Juguetería',
	FARMACIA = 'Farmacia',
	CUIDADO_PERSONAL = 'Cuidado Personal',
	MAQUILLAJE = 'Maquillaje',
	FLORISTERIA = 'Floristería',
	TIENDA = 'Tienda',
	SUPERMERCADOS = 'Supermercados',
	LIBRERIA = 'Librería',
	JUGUERIA = 'Juguería',
	OTRO = 'Otro',
}
